FROM node:18-alpine
WORKDIR /usr/app

COPY package.json ./
RUN npm install --omit=dev

# in monorepo sitations skip following
# RUN npm ci --only=production

# Bundle app source
COPY dist .

EXPOSE 5000
CMD ["node", "index.js"]